namespace PromptEvaluator.Models;

public class EvaluatorOptions
{
    public const string SectionName = "Evaluator";

    /// <summary>Path to the dataset JSON file generated by the Python notebook.</summary>
    public string DatasetFile { get; set; } = "Data/dataset.json";

    /// <summary>Path to the prompt configuration YAML file.</summary>
    public string PromptFile { get; set; } = "Data/prompt.yaml";

    /// <summary>Output path for the raw JSON results.</summary>
    public string JsonOutputFile { get; set; } = "Data/output.json";

    /// <summary>Output path for the HTML evaluation report.</summary>
    public string HtmlOutputFile { get; set; } = "Data/output.html";

    /// <summary>Maximum number of test cases evaluated in parallel.</summary>
    public int MaxConcurrentTasks { get; set; } = 3;
}
