
namespace PromptEvaluator.Models;

/// <summary>One entry from dataset.json (generated by the Python dataset generator).</summary>
public class TestCase
{
    [JsonPropertyName("scenario")]
    public string Scenario { get; set; } = string.Empty;

    [JsonPropertyName("task_description")]
    public string TaskDescription { get; set; } = string.Empty;

    [JsonPropertyName("prompt_inputs")]
    public Dictionary<string, string> PromptInputs { get; set; } = [];

    [JsonPropertyName("solution_criteria")]
    public List<string> SolutionCriteria { get; set; } = [];
}
